spring:
  application:
    name: movie-demo
  data:
    rest:
      base-path: movie-adapter/api
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      jdbc:
        batch_size: 500
        order_inserts: true
        order_updates: true
    properties:
      hibernate:
        default_schema: movie_adapter
        jdbc:
          lob:
            # see https://github.com/pgjdbc/pgjdbc/issues/1102
            non_contextual_creation: true
  cloud:
    stream:
      bindings:
        output:
          destination: movie-title-exchange
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  profiles: local
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/movie
    username: postgres
    password: admin
---
spring:
  profiles: container
  datasource:
    platform: postgres
    url: jdbc:postgresql://movie-postgres:5432/movie
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}